project:
  output-dir: ./_site/zh

website:
  title: "watsy0007"
  site-url: https://watsy0007.com
  repo-url: https://github.com/watsy0007/watsy0007.github.io
  navbar:
    left:
      - text: 博客
        href: blog.qmd
      - text: 关于
        href: about.qmd
    right:
      - text: English
        href: ../
      - icon: rss
        href: blog.xml
format:
  html:
    theme: simplex
    css: styles.css
    include-in-header: plausible.html

lang: zh
