project:
  type: website
  output-dir: docs

website:
  title: "watsy0007"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/watsy0007
format:
  html:
    theme: simplex
    css: styles.css



