project:
  type: website
  output-dir: docs

website:
  title: "watsy0007"
  site-url: https://watsy0007.com
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/watsy0007
      - icon: rss
        href: index.xml
format:
  html:
    theme: simplex
    css: styles.css



