on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render CN
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: zh
        with:
          to: html
      - name: Render EN
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en
        with:
          to: html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-content
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: site-content
          path: _site
      - name: deploy gh-pages
        run: |
          git config --global user.email "gh-pages-action@github.com"
          git config --global user.name "gh-pages-action"
          cp -r _site/en/* .
          cp -r _site/zh .
          rm -rf _site
          git add .
          git commit -m "update gh-pages"
          git push -f origin HEAD:gh-pages
          echo "done"
